### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by karamusluk** [AbdullahWali/Spotify-Lyrics#1]
When i try to get the 
api running on port 3000
Access localhost:3000 to see the lyrics for the currently played song

that opening page with link 
https://accounts.spotify.com/authorize?client_id=xxxxxxx&response_type=code&redirect_uri=http://localhost:3000/callback/&scope=user-read-playback-state&state=spotify_auth_state

gives me INVALID_CLIENT: Invalid redirect URI.

What should I Do?
Thanks

**Comment by AbdullahWali** [comment]
3. While in the same window (Spotify Application), add the following url to Redirect URIs: http://localhost:3000/callback

did you do this step?
